server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  #config native 사용을 위한 설정 값
  profiles:
    active: native
  cloud:
    config:
      #config native 사용을 위한 설정 값 
      server:
        native:
          search-locations: file://${user.home}/msa_study_config
          #search-locations: file:///Users/tjjeong/msa_study_config ㅋ
        #git:
          #uri: file:///Users/tjjeong/git/msa-study
          #uri: https://github.com/yarisong/msa-study #git hub url 
          #default-label: feature-gateway
managemnet:
  endpoints:
    web:
      exposure:
        include: health, busrefresh